stateDiagram-v2
    [*] --> НаближенняАвто
    
    state МодульВїзду {
        НаближенняАвто --> РозпізнаванняНомера
        РозпізнаванняНомера --> ЗапитДоБД
        
        state check_db <<choice>>
        ЗапитДоБД --> check_db
        
        check_db --> ЧорнийСписок : Авто в розшуку / Боржник
        check_db --> Резидент : Є діючий абонемент
        check_db --> Гість : Немає в базі
    }
    
    ЧорнийСписок --> БлокуванняВїзду
    БлокуванняВїзду --> ВикликОхорони
    ВикликОхорони --> [*]
    
    Резидент --> ФіксаціяВїзду
    Гість --> ВидачаТалону
    ВидачаТалону --> ФіксаціяВїзду
    
    ФіксаціяВїзду --> ВідкриттяШлагбаума
    ВідкриттяШлагбаума --> ПаркуванняАвто
    
    state ПроцесОплати {
        ПаркуванняАвто --> ПідхідДоТерміналу
        ПідхідДоТерміналу --> СкануванняТалону
        СкануванняТалону --> РозрахунокСуми
        
        state fork_pay <<fork>>
        РозрахунокСуми --> fork_pay
        fork_pay --> Готівка
        fork_pay --> Картка_NFC
        fork_pay --> МобільнийДодаток
        
        state join_pay <<join>>
        Готівка --> join_pay
        Картка_NFC --> join_pay
        МобільнийДодаток --> join_pay
        
        join_pay --> ВалідаціяПлатежу
        
        state check_pay <<choice>>
        ВалідаціяПлатежу --> check_pay
        check_pay --> ПомилкаПлатежу : Відмова
        ПомилкаПлатежу --> ПідхідДоТерміналу : Повторити
        
        check_pay --> ОплатаУспішна : OK
        ОплатаУспішна --> ДрукЧеку
        ДрукЧеку --> ЗапускГрейсПеріоду
    }
    
    ЗапускГрейсПеріоду --> ВиїздЗПаркінгу
    ВиїздЗПаркінгу --> ВідкриттяШлагбаумаВиїзд
    ВідкриттяШлагбаумаВиїзд --> [*]